export { Navbar } from './Navbar'
export { About } from './About'
export { Cursos } from './Cursos'
export { Card } from './Card'
export { Contact } from './Contact'
export { Footer } from './Footer'
export { Curso } from './Curso'
export { Gallery } from './Gallery'